server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/muhanparking?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true    # 쿼리 볼수 있게
    open-in-view: false

  # 파일 업로드 설정 (나중에 필요함)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug  # 콘솔에 쿼리 보이게
    com.example.muhanparking: debug  # 패키지는 debug 레벨로

jwt:
  secret: "your-secret-key-please-change-this-to-something-secure" # 실제로는 더 복잡한 값 사용해야 함