server:
  port: 60010
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/muhanparking
    username: root
    password: root
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true
        generate_statistics: false
    show-sql: true


logging:
  level:
    org.springframework.security: debug
    org.hibernate.SQL: debug  # 콘솔에 쿼리 보이게
    com.example.muhanparking: debug  # 패키지는 debug 레벨로

jwt:
  secret: "your-secret-key-please-change-this-to-something-secure" # 실제로는 더 복잡한 값 사용해야 함